import { Inter } from 'next/font/google';
import './globals.css'
import Header from './_components/Header/Header';
import Footer from './_components/Footer/Footer';
import UserContextProvider from '@/context/User/UserContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserContextProvider>
          <Header />
          {children}
          <Footer />
        </UserContextProvider>
      </body>
    </html>
  );
}
